export const mobilityType = [
  "All-Terrain Vehicle (ATV)",
  "Bike",
  "Bus",
  "Heavy Motorcycle",
  "Light Motorcycle Category (LMC)",
  "Light Personnel Troop Carrier",
  "Light Transport Vehicle (LTV)",
  "Motorcycle",
  "Patrol Car",
  "Patrol Jeep",
  "Personnel Carrier",
  "Personnel Troop Carrier",
  "Rescue Boat",
  "Truck",
];
